### ISSUE TITLE
wrong source url

### ISSUE THREAD

**Issue by matyaskopp** [hpreki/ParCzech4AT#3]
https://github.com/hpreki/ParCzech4AT/blob/36d41e72082504343de1c3923cc718c25d6daf28/sample-data-AT/ParlaMint-AT_1996-01-15-020_XX_NRSITZ_00002.xml#L57

should be:
```XML
 <idno type="URI">https://www.parlament.gv.at/PAKT/VHG/XX/NRSITZ/NRSITZ_00002/fnameorig_113993.html</idno> 
```

**Comment by hpreki** [comment]
fixed
